Fix ID token issuer field to match discovery data
diaspora/diaspora pull request #7081
Opened 2016-09-10 10:49 UTC by cmrd-senya

OpenID Connect spec says:

"The issuer returned by discovery MUST exactly match the value of iss in the ID Token."

https://openid.net/specs/openid-connect-core-1_0.html#IssuerIdentifier

2016-09-10 10:51 UTC, cmrd-senya commented on lib/api/openid_connect/id_token.rb
> +        Rails.application.routes.url_helpers.root_url(Rails.application.config.action_mailer.default_url_options)
I don't like referring `Rails.application.config.action_mailer` here. I thought of setting `Rails.application.routes.default_url_options` globally for production environment (currently it is set only in tests). However I'm unsure if it's okay.

2016-09-20 02:26 UTC, denschub commented on lib/api/openid_connect/id_token.rb
> +        Rails.application.routes.url_helpers.root_url(Rails.application.config.action_mailer.default_url_options)
No objections. Feel free.

2016-09-20 02:26 UTC, skyschub requested changes
Looks good, feel free to change to `root_url` implementation. :)

2016-10-24 00:00 UTC, cmrd-senya commented
updated

2016-10-27 00:31 UTC, closed without merging

2016-10-27 00:31 UTC, denschub commented
Merged as a80806ca58dc8ccd8ffc0e290e8b6963fa68cb98. Thanks.