Refactor SPV post interactions
diaspora/diaspora pull request #7089
Opened 2016-09-12 00:10 UTC by svbergerem

Fixes #4425 and #5305.

2016-09-20 02:28 UTC, denschub commented on app/assets/templates/single-post-viewer/single-post-interaction-counts_tpl.jst.hbs
> +          {{{personImage this 'small' 'micro'}}}
Handlebar helpers support double qoutes. Might be a good place to start adopting if we're on that file.

2016-09-20 02:29 UTC, skyschub requested changes

2016-09-20 19:44 UTC, svbergerem commented on app/assets/templates/single-post-viewer/single-post-interaction-counts_tpl.jst.hbs
> +          {{{personImage this 'small' 'micro'}}}
Done.

2016-09-25 01:07 UTC, closed without merging

2016-09-25 01:07 UTC, denschub commented
Merged as 709547860a7ecd3f7c113f120c7c60f96f5586a2, thanks.