Extract inline js
diaspora/diaspora pull request #7113
Opened 2016-09-19 20:46 UTC by SuperTux88

I extracted some of the inline JS-code to external JS-files.

* Tags autocomplete: I unified the code for the tags autocompletion, so it isn't copied everywhere, because it was mainly the same.
* Profile photo uploader: Just copied to a JS file and use translations from JS-I18n, so I could delete the other (duplicate) translations.
* Trigger the getting started popovers from backbone via gon.
* Trigger background search timer with gon
* Extract mobile bookmarklet JS to separate file and use the already available data from gon.

I also removed some unused JS-files from the precompile list.

I still need to initialize tags autocomplete and profile photo uploader from inline JS on mobile, if somebody knows where I can move this, please tell me (on desktop I used backbone, but I couldn't find something similar for mobile to only initialize them on specific pages).

2016-09-20 23:05 UTC, diaspora-code-review commented on app/assets/javascripts/mobile/mobile_profile_edit.js
> +$(document).ready(function() {
Block must not be padded by blank lines.

2016-09-25 01:10 UTC, denschub commented
@svbergerem, could you have a look please?

2016-09-25 01:10 UTC, denschub commented
(sorry, hit the wrong button. didn't mean to close.)

2016-09-28 07:09 UTC, svbergerem requested changes

2016-09-28 07:09 UTC, svbergerem commented on app/assets/javascripts/helpers/tags_autocomplete.js
> +      emptyText: "no_results"
This should be `Diaspora.I18n.t("no_results")`.

2016-09-28 07:09 UTC, svbergerem commented on app/assets/javascripts/pages/users-getting-started.js
>        }
Add `preFill: gon.preloads.tagsArray` and add the gon preload to the getting_started method of the users controller.

2016-09-28 07:09 UTC, svbergerem commented on app/views/users/getting_started.mobile.haml
> +      new Diaspora.TagsAutocomplete("#follow_tags");
Add `preFill: gon.preloads.tagsArray`.

2016-09-28 19:53 UTC, svbergerem approved these changes

2016-09-28 20:04 UTC, closed without merging

2016-09-28 20:04 UTC, svbergerem commented
Thank you! :+1: