Report view
diaspora/diaspora pull request #7180
Opened 2016-11-10 12:35 UTC by SansPseudoFix

Before:
![old_report_view](https://cloud.githubusercontent.com/assets/6507951/20176512/708b8d58-a748-11e6-8cfe-c61fb3c6093d.png)

This PR:
![new_report_view](https://cloud.githubusercontent.com/assets/6507951/20176517/7735f242-a748-11e6-888a-b6f5255ea13e.png)

I think it's more logical to display **reason** and **reported by** on the same line. Besides sometimes **Post** sections are displayed on 2 or 3 lines, and break headers.

I also now display full message on **Post** section, because, as a podmin, sometimes one and half line is not enough to understand report without clicking on it. I think it can be usefull for spam, for instance: you have the full message and don't have to click on every spam message to delete them.

I was thinking to truncate messages (20 lines?) but my ruby skills are very limited. Any help appreciated :)

2016-11-10 12:45 UTC, SuperTux88 commented
I think the Post/Comment should stay the "title" (because it is the main-item of the report). On bigger pods the same spam-post gets reported multiple times, it would be better to move the reporter down to the body and combine all reports for the same post/comment and make a list like:
* reporter 1: reason 1
* reporter 2: reason 2

2016-11-10 12:59 UTC, SansPseudoFix commented
> On bigger pods the same spam-post gets reported multiple times, it would be better to move the reporter down to the body and combine all reports for the same post/comment and make a list like:

Would be definitely great but totally out of my skills :)

2016-11-23 09:35 UTC, AugierLe42e commented
I think this is a good improvement. The post can be potentially long and then, it feels weird that it is the title rather than the content.

2016-11-23 14:25 UTC, goobertron commented
I agree with @SuperTux88, but combining reports on the same post is perhaps out of scope of this PR. It is important that the entire post be visible to the podmin, however. Perhaps a useful first step would be to add a roll-over behaviour so that the entire post appears in a pop-up?

2016-11-23 16:07 UTC, denschub commented
Oh god no please no popup.

I don't think it's needed to have a large area for the report reason. It's a small input box anyway, so people don't write essays there. The post is usually larger than the report reason, so using the larger area for the actual content seems reasonable. I'm fine with this from a UX perspective, but I have not done any code review.

2016-11-23 17:42 UTC, AugierLe42e commented
Code looks fine to me.

2016-11-23 18:20 UTC, goobertron commented
When I said 'I agree with SuperTux' above, I actually meant that I agree that combining reports on the same post would be good. The new UI, with the post in the body of the report, looks more natural to me, but I don't maintain a pod so can't comment whether it's as useful to podmins.

In order to combine reports as suggested, you could simply add extra lines in the grey header bar of the new UI, such as:

> Reason: offensive content         Reported by minus
> Reason: spam                           Reported by fred
> Reason: offensive content         Reported by Jane

with the post text in the white area below.

Would that be acceptable?

2016-12-01 11:45 UTC, AugierLe42e commented
I think it's a bit difficult for @SansPseudoFix and out of scope of this PR.

2016-12-01 11:58 UTC, SansPseudoFix commented
> I think it's a bit difficult for @SansPseudoFix and out of scope of this PR.

I can't agree more. This PR is about unification and "UX", that's all.

2016-12-01 13:57 UTC, skyschub requested changes

2016-12-01 13:57 UTC, denschub commented on app/views/report/index.html.haml
> +                  = raw t("report.reason_label", text: report.text)
Huge XSS issue via the report reason.

2016-12-02 12:16 UTC, SansPseudoFix commented
Ok, no more XSS issue :)

2016-12-02 13:37 UTC, diaspora-code-review commented on app/assets/stylesheets/report.scss
> +  }
Rule declaration should be followed by an empty line

2016-12-02 13:46 UTC, SansPseudoFix commented on app/assets/stylesheets/report.scss
> +  }
oO

2016-12-02 13:50 UTC, Flaburgan commented on app/assets/stylesheets/report.scss
> +  }
There should be an empty line between `}` and the following `.content {`

2016-12-13 23:25 UTC, skyschub approved these changes

2016-12-14 18:59 UTC, Flaburgan approved these changes
Tested locally with Firefox, works fine.

2017-01-05 16:33 UTC, SansPseudoFix commented
Ping?

2017-01-15 03:05 UTC, closed without merging

2017-01-15 03:06 UTC, svbergerem commented
Merged as 0f60b9fb949f51abde379e34e66ffabfca1a38df. Thank you!