Single post view interaction refactorings
diaspora/diaspora pull request #7182
Opened 2016-11-12 14:42 UTC by svbergerem

Fixes #6314. Related to #7168.

This loads the first 30 likes and reshares via gon and adds a 'Show all' link if there are more. Clicking on the link will fetch all likes or reshares.

![show all likes](https://cloud.githubusercontent.com/assets/3798614/20238528/024d84f2-a8ee-11e6-8a46-54cccc686468.png)

Comments are still fetched via Ajax.

2017-05-16 08:51 UTC, svbergerem commented
There was a small conflict with #7419: the timeago in the single post view didn't work anymore. I fixed that while rebasing the PR.

2017-05-16 15:37 UTC, cmrd-senya requested changes
I didn't manage to review all changes of the PR, only a part of them. I'll continue with it in a few days.

2017-05-16 20:40 UTC, svbergerem commented on app/assets/javascripts/app/views/single-post-viewer/single_post_interaction_counts.js
> +    "#show-all-comments"
Thanks! There is no need for a tooltip, so I removed the lines.

2017-05-21 22:17 UTC, cmrd-senya approved these changes
Looks good to me, but here are some notes on the code

2017-05-21 22:17 UTC, cmrd-senya commented on spec/presenters/post_presenter_spec.rb
> +    end
I think these tests could be a little smarter and verify the contents of the hash. This data isn't checked anywhere now.

2017-07-26 08:55 UTC, svbergerem commented on app/assets/javascripts/app/router.js
> +    this.renderPage(function() { return new app.pages.SinglePostViewer({id: id, el: $("#container")}); });
I was pretty sure that there is a reason for this but I also had to search for a while. Without this change the timeagos in the single post view are missing and only appear after a few seconds. That's the conflict I mentioned [here](https://github.com/diaspora/diaspora/pull/7182#issuecomment-301717784). I'll move this change to a new commit.

2017-07-26 09:51 UTC, svbergerem commented on spec/presenters/post_presenter_spec.rb
> +    end
Done.

2017-08-12 14:48 UTC, skyschub approved these changes

2017-08-12 14:50 UTC, denschub commented
@svbergerem mind rebasing this?

2017-08-12 15:59 UTC, svbergerem commented
@denschub Done.

2017-08-12 17:16 UTC, merged

2017-08-12 17:18 UTC, SuperTux88 commented
Merged (after 9 months ;) ), thanks everyone ❤️