Remove unused posts/photo view
diaspora/diaspora pull request #7208
Opened 2016-11-20 21:58 UTC by svbergerem

2016-11-22 02:34 UTC, SuperTux88 requested changes

2016-11-22 02:34 UTC, SuperTux88 commented on app/views/posts/_photo.html.haml
> -= link_to t('photos.show.show_original_post'), post_path(post.status_message)
We can also remove this translation.

2016-11-22 07:35 UTC, svbergerem commented on app/views/posts/_photo.html.haml
> -= link_to t('photos.show.show_original_post'), post_path(post.status_message)
Thanks, done.

2016-11-23 00:51 UTC, SuperTux88 approved these changes

2016-11-23 00:54 UTC, closed without merging

2016-11-23 00:55 UTC, SuperTux88 commented
Merged as 858884491328f932c3bede67c3362bc8b0ecf771 and 9556669761c48b82a9d8ea5251daa725d2b677a8

Thanks for the cleanup :)