CSRF mail less disturbing
diaspora/diaspora pull request #7238
Opened 2016-12-03 13:56 UTC by SansPseudoFix

Changes based on the conversation on #7193. I kept @goobertron text [here](https://github.com/diaspora/diaspora/issues/7193#issuecomment-263902310) and changed "account" by "session" as mentioned [here](https://github.com/diaspora/diaspora/issues/7193#issuecomment-263949350) by @SuperTux88

2016-12-03 17:39 UTC, SuperTux88 requested changes

2016-12-03 17:39 UTC, SuperTux88 commented on config/locales/diaspora/en.yml
> +        If you see this message regularly, please check your browsing settings.
> If you see this message repeatedly, please check the points above, including any browser add-ons.

As mentioned here: https://github.com/diaspora/diaspora/issues/7193#issuecomment-263936222

2016-12-04 18:04 UTC, SuperTux88 commented on config/locales/diaspora/en.yml
> +        If you see this message regularly, please check your browsing settings.
Changed it myself and fixed the broken spec.

2016-12-04 18:04 UTC, SuperTux88 approved these changes

2016-12-04 18:14 UTC, SansPseudoFix commented on config/locales/diaspora/en.yml
> +        If you see this message regularly, please check your browsing settings.
Sorry for missing regularly -> repeatedly. I was planning to do it tomorrow but it's cool, thx!

2016-12-04 18:17 UTC, SuperTux88 commented on config/locales/diaspora/en.yml
> +        If you see this message regularly, please check your browsing settings.
No worries, we are planning to freeze tonight, so I thought I do it myself, since it's a quick fix :)

2016-12-04 19:10 UTC, closed without merging

2016-12-04 19:10 UTC, denschub commented
Merged as 6c37171f9f37edcb79770c1c37c609d692f0d4b4 61300dab592537d846c1c05d273841752e4551b5, gracias.

2016-12-04 22:38 UTC, Flaburgan commented
Thanks @SansPseudoFix and thanks for the merge. Would it be possible to push the strings to webtranslateit so the email will be localized in the 0.6.2 release?

2016-12-04 23:52 UTC, denschub commented
> Would it be possible to push the strings to webtranslateit

yes, sure! Thanks for the reminder, pushed it now.