Add links to the aspects and followed tags pages on mobile
diaspora/diaspora pull request #7265
Opened 2017-01-03 12:11 UTC by Flaburgan

Close https://github.com/diaspora/diaspora/issues/6385

2017-01-03 12:12 UTC, diaspora-code-review commented on features/step_definitions/user_steps.rb
> +  post = @me.post :status_message, text: text, to: @me.aspects.where(name: aspect_name).first.id
Useless assignment to variable - `post`.

2017-01-03 12:15 UTC, Flaburgan commented on features/step_definitions/user_steps.rb
> +  post = @me.post :status_message, text: text, to: @me.aspects.where(name: aspect_name).first.id
Well yeah, this is weird, I forgot to `post.save` here but the test is green anyway oO, [this line](https://github.com/diaspora/diaspora/pull/7265/files#diff-b0f17d137a09c6491e446c550000d479R66) should fail...

2017-01-03 12:26 UTC, SuperTux88 commented on features/step_definitions/user_steps.rb
> +  post = @me.post :status_message, text: text, to: @me.aspects.where(name: aspect_name).first.id
I think `.post` already saves the post.

2017-01-03 17:21 UTC, Flaburgan commented on features/step_definitions/user_steps.rb
> +  post = @me.post :status_message, text: text, to: @me.aspects.where(name: aspect_name).first.id
Confirmed. I corrected, ready to review.

2017-01-06 14:09 UTC, svbergerem requested changes

2017-01-06 14:09 UTC, svbergerem commented on features/step_definitions/user_steps.rb
> +
Please move this to `features/step_definitions/posts_steps.rb`.

2017-01-06 17:58 UTC, Flaburgan commented
@svbergerem done.

2017-01-07 02:03 UTC, svbergerem approved these changes

2017-01-07 02:05 UTC, closed without merging

2017-01-07 02:06 UTC, svbergerem commented
Thanks!

2017-01-07 02:08 UTC, Flaburgan commented
Awesome! Thank you ;)