Update database config comments
diaspora/diaspora pull request #7282
Opened 2017-01-15 19:52 UTC by svbergerem

2017-01-15 19:57 UTC, Flaburgan approved these changes
Nice check thank you!

2017-01-15 22:28 UTC, SuperTux88 approved these changes

2017-01-15 22:39 UTC, SuperTux88 requested changes

2017-01-15 22:39 UTC, SuperTux88 commented on config/database.yml.example
> +# Comment the the postgresql line and uncomment the mysql line
Oh, can you also remove the double "the the"?

2017-01-15 23:14 UTC, svbergerem commented on config/database.yml.example
> +# Comment the the postgresql line and uncomment the mysql line
done

2017-01-15 23:39 UTC, SuperTux88 approved these changes

2017-01-16 00:18 UTC, closed without merging

2017-01-16 00:18 UTC, SuperTux88 commented
Merged as b508b9f6ef7282e782e91663705637bc3af87a94

Thanks 👍