Add Liberapay button in the donate section
diaspora/diaspora pull request #7290
Opened 2017-01-22 01:51 UTC by Flaburgan

https://liberapay.com/

Liberapay is a recurrent donations platform (quite like patreon, but freesoftware ;)). I'd like to integrate its donation button (without any external requests :)) to the donate section of the left side bar.

2017-01-22 01:52 UTC, diaspora-code-review commented on app/views/streams/main_stream.html.haml
> +        - if AppConfig.settings.paypal_donations.enable? || AppConfig.settings.liberapay.enable? || AppConfig.bitcoin_donation_address
Line is too long. [134/120]

2017-01-22 06:05 UTC, SuperTux88 requested changes

2017-01-22 06:05 UTC, SuperTux88 commented on app/views/streams/main_stream.html.haml
> +        - if AppConfig.settings.paypal_donations.enable? || AppConfig.settings.liberapay.enable? || AppConfig.bitcoin_donation_address
We should create a method `donations_enabled?` in the `AppConfig` or `ApplicationHelper`.

2017-01-22 06:05 UTC, SuperTux88 commented on app/views/shared/_donatepod.html.haml
> +    = image_tag "buttons/liberapay-button.svg", alt: "Donate", title: "Donate to liberapay"
Please make these Strings translatable.

2017-01-22 09:21 UTC, diaspora-code-review commented on app/helpers/application_helper.rb
> +    AppConfig.settings.paypal_donations.enable? || AppConfig.settings.liberapay.username.present? || AppConfig.bitcoin_donation_address
Line is too long. [135/120]

2017-01-22 09:40 UTC, diaspora-code-review commented on features/step_definitions/custom_web_steps.rb
> +  find("#liberapay-button")['href'].should == "https://liberapay.com/BBBBBB/donate"
Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.

2017-01-22 09:42 UTC, Flaburgan commented
Corrected the remarks and added a test ;)

2017-01-22 10:16 UTC, diaspora-code-review commented on app/views/shared/_donatepod.html.haml
> +    = image_tag "buttons/liberapay-button.svg", alt: t("aspects.index.donate"), title: t("aspects.index.donate_liberapay")
Line is too long. [122/120]

2017-01-22 15:08 UTC, SuperTux88 requested changes

2017-01-22 15:08 UTC, SuperTux88 commented on app/views/shared/_donatepod.html.haml
> +    = image_tag "buttons/liberapay-button.svg", alt: t("aspects.index.donate"), title: t("aspects.index.donate_liberapay")
You can write the `title` in the next line.

2017-01-22 18:27 UTC, Flaburgan commented
We should be ready to go, I even added the changelog entry ;)

2017-01-22 18:59 UTC, SuperTux88 requested changes
Sorry, I only looked at the code before, but now after testing it in the browser I saw that it's broken when you enable all 3 of the donation settings.

![spectacle a14304](https://cloud.githubusercontent.com/assets/458548/22184949/6078e168-e0dc-11e6-8569-321af1cdfe41.png)

I think we should make it like this:

Paypal:  
[Button]  
Liberapay:  
[Button]  
Bitcoin:  
[input-field]

(currently the input field for bitcoin is also on the same line as "Bitcoin:", so it's theoretically out of scope here, but I would change that too.)

2017-01-22 18:59 UTC, SuperTux88 commented on app/views/streams/main_stream.html.haml
> -
Nit: lets keep this newline (all `section`s are separated with an empty line)

2017-01-22 20:36 UTC, diaspora-code-review commented on app/views/shared/_donatepod.html.haml
> +        %input{name: "hosted_button_id", type: "hidden", value: AppConfig.settings.paypal_donations.paypal_hosted_button_id}
Line is too long. [124/120]

2017-01-22 20:36 UTC, diaspora-code-review commented on app/views/shared/_donatepod.html.haml
> +      -if AppConfig.settings.paypal_donations.paypal_unhosted_button_encrypted.present?
The - symbol should have one space separating it from code

2017-01-22 20:36 UTC, diaspora-code-review commented on app/views/shared/_donatepod.html.haml
> +        %input{name: "encrypted", type: "hidden", value: AppConfig.settings.paypal_donations.paypal_unhosted_button_encrypted}
Line is too long. [126/120]

2017-01-22 20:36 UTC, diaspora-code-review commented on app/views/shared/_donatepod.html.haml
> +      %input{name: "submit", type: "submit", value: t("aspects.index.donate"), class: "btn btn-default"}
Avoid defining `class` in attributes hash for static class names

2017-01-22 21:01 UTC, SuperTux88 commented on app/views/shared/_donatepod.html.haml
> +        %input{name: "hosted_button_id", type: "hidden", value: AppConfig.settings.paypal_donations.paypal_hosted_button_id}
Just write the `value` on the next line:
```haml
        %input{name: "hosted_button_id", type: "hidden",
               value: AppConfig.settings.paypal_donations.paypal_hosted_button_id}
```

2017-01-22 21:02 UTC, SuperTux88 commented on app/views/shared/_donatepod.html.haml
> +        %input{name: "encrypted", type: "hidden", value: AppConfig.settings.paypal_donations.paypal_unhosted_button_encrypted}
Some as above, `value` on next line.

2017-01-22 21:03 UTC, SuperTux88 commented on app/views/shared/_donatepod.html.haml
> +      %input{name: "submit", type: "submit", value: t("aspects.index.donate"), class: "btn btn-default"}
```haml
%input.btn.btn-default{name: "submit", type: "submit", value: t("aspects.index.donate")}
```

2017-01-22 21:04 UTC, SuperTux88 requested changes
Just fix the 3 last code-review remarks (I don't know why github marked it as outdated), and it should be good to merge :)

2017-01-22 21:56 UTC, Flaburgan commented
I had already fixed one ;)
Everything should be fine now.

2017-01-22 22:01 UTC, SuperTux88 approved these changes
Thanks 👍 Pronto is happy now, and I'm happy too. Waiting for travis to be happy too... ;)

2017-01-22 22:31 UTC, closed without merging

2017-01-22 22:32 UTC, SuperTux88 commented
Merged as 1028632ac1e393504516deaf588d4fbb7da1027d

Thank you :)

2017-02-07 00:17 UTC, trebmuh commented
:+1: awesome