Issue#7279 Disallow blocking admins
diaspora/diaspora pull request #7309
Opened 2017-02-05 00:36 UTC by spixi

This fixes a part of Issue#7279. It is now unpossible to block admins.

2017-02-05 00:36 UTC, diaspora-code-review commented on app/models/block.rb
> +    errors[:person_id] << t('blocks.create.failure.podmin') if Role.exists?(person_id: self.person_id, name: "admin")
- Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
- Redundant `self` detected.

2017-02-05 00:36 UTC, diaspora-code-review commented on spec/models/block_spec.rb
> +    end
unexpected token kEND
(Using Ruby 2.2 parser; configure using `TargetRubyVersion` parameter, under `AllCops`)

2017-02-05 01:05 UTC, spixi commented
Alice is an admin, so it seems that I broke ```features/desktop/blocks_user.feature``` :(

2017-02-05 01:12 UTC, SuperTux88 requested changes
First: Please use pronto locally and review your PR before submitting it, you again needed 3 tries to create it and every push starts a travis run (luckily the first two failed fast).

And I think we shouldn't disallow to block podmins, because my personal account has also the admin role, but I still want to allow people to ignore me. So it would be better to just allow all podmins to send messages, even when they don't share or are blocked, like also described in #7297.

2017-02-05 01:19 UTC, spixi commented on Changelog.md
> +* admins cannot be blocked anymore [#7279](https://github.com/diaspora/diaspora/issues/7297)
Ok, just drop the PR. It was a try. I realize that this is the wrong way to implement this. I see you can still unshare the admin.

2017-02-05 01:24 UTC, SuperTux88 commented on Changelog.md
> +* admins cannot be blocked anymore [#7279](https://github.com/diaspora/diaspora/issues/7297)
You can still use this PR to fix it another way, or you can close it yourself if you don't want to work at this issue anymore.

2017-02-20 23:06 UTC, denschub commented
16 days since

> You can still use this PR to fix it another way, or you can close it yourself if you don't want to work at this issue anymore.

and no reaction. Closing this.

2017-02-20 23:06 UTC, closed without merging