support command+enter on MacOS to submit post
diaspora/diaspora pull request #7409
Opened 2017-04-01 08:24 UTC by rajanak

Fixes #7273

2017-04-01 08:25 UTC, diaspora-code-review commented on app/assets/javascripts/app/views/comment_stream_view.js
> +    if(evt.which === Keycodes.ENTER && (evt.metaKey || evt.ctrlKey)) {
Expected space(s) after "if".

2017-04-01 08:25 UTC, diaspora-code-review commented on app/assets/javascripts/app/views/conversations_form_view.js
> +    if(evt.which === Keycodes.ENTER && (evt.metaKey || evt.ctrlKey)) {
Expected space(s) after "if".

2017-04-01 08:25 UTC, diaspora-code-review commented on app/assets/javascripts/app/views/publisher_view.js
> +    if(evt.which === Keycodes.ENTER && (evt.metaKey || evt.ctrlKey)) {
Expected space(s) after "if".

2017-04-02 20:54 UTC, SuperTux88 requested changes
Thanks for the pull request. Looks good to me so far. 👍 

Can you please add some tests like we now have with the `ctrlKey` also with the `metaKey`? And then can you squash the commits to a single one?

2017-08-12 12:31 UTC, SuperTux88 commented
Superseded by #7524

2017-08-12 12:31 UTC, closed without merging