Add access to the report page on mobile for moderators
diaspora/diaspora pull request #7479
Opened 2017-07-05 07:05 UTC by Flaburgan

Follow up of #7295 where I forgot about the moderator role. This PR add a link in the mobile drawer to allow moderators to access the report page.
I also added a test to be sure that those links are not displayed to normal users.

@SuperTux88 I know you branched 0.6.7.0 tonight, as you're the one who dispatches commits everywhere, you decide if this can be included in it or not ;) (The review should be very easy).

2017-07-06 00:41 UTC, SuperTux88 requested changes
Only a small change

2017-07-06 00:41 UTC, SuperTux88 commented on app/views/layouts/_drawer.mobile.haml
> +      - if current_user.moderator? && !current_user.admin?
Can you do that the same way [as it is done on desktop](https://github.com/diaspora/diaspora/blob/526ebcfa13a799cae6bfbcc822c958ebecfa4d2b/app/assets/templates/header_tpl.jst.hbs#L102-L106)? So put it as `- elsif current_user.moderator?` below the `- if current_user.admin?` block, then you don't need `&& !current_user.admin?`

2017-07-06 07:09 UTC, Flaburgan commented on app/views/layouts/_drawer.mobile.haml
> +      - if current_user.moderator? && !current_user.admin?
Sure! Done. I wasn't satisfied by this solution but didn't think about that. I was surprised to discover that the `current_user.moderator?` returns `true` for admins.

2017-07-07 06:58 UTC, SuperTux88 approved these changes

2017-07-07 07:05 UTC, closed without merging

2017-07-07 07:05 UTC, SuperTux88 commented
Uplifted to 0.6.7.0 and merged as 2dc142bd70797bd00beebc6a5bccbf35d4234d4b

Thank you! 👍