Add markdown editor on conversations and comments
diaspora/diaspora pull request #7482
Opened 2017-07-06 16:40 UTC by cmrd-senya

This is a follow up for #7214.

I fixed all the notes by @svbergerem and rebased the code.

I didn't do thorough review or test myself, so this needs review. Maybe I'll do one myself if nobody else does it earlier.

2017-07-06 17:12 UTC, goobertron commented
Great, thanks!

2017-07-12 23:34 UTC, cmrd-senya commented
Okay, I reviewed the code and made some changes I found desirable. For me it looks good now. I think we need a one more review now, possibly from @svbergerem to merge it.

2017-08-09 14:29 UTC, svbergerem requested changes
Just some minor remarks. Everything else looks good. Please squash the commits afterwards.

2017-08-09 14:29 UTC, svbergerem commented on spec/javascripts/helpers/markdown_editor_spec.js
> +
Please add `returns false if the editor is in write mode`.

2017-08-09 14:29 UTC, svbergerem commented on spec/javascripts/helpers/markdown_editor_spec.js
> +
As written above, I think this method should be called `userInputEmpty` and behave accordingly. Afterwards please add a test `returns true if the editor is empty`.

2017-08-09 18:35 UTC, cmrd-senya commented
I squashed and rebased everything that was done before your notes. For your notes I added changes as a fixup commit so you could check what I changed exactly.

2017-08-09 19:50 UTC, svbergerem approved these changes

2017-08-09 19:52 UTC, svbergerem commented
I squashed the fixup commit while merging. Thank you! :)

2017-08-09 19:52 UTC, closed without merging

2017-08-09 20:07 UTC, Flaburgan commented
Just pushed that change to diaspora-fr. Thank you two VERY MUCH for your work!

2017-08-09 21:55 UTC, goobertron commented
Yes, a HUGE thank you to @cmrd-senya and @svbergerem!

2017-08-09 22:03 UTC, cmrd-senya commented
And to @AugierLe42e who developed the original code!