Improve responsive header in desktop version
diaspora/diaspora pull request #7509
Opened 2017-07-31 19:56 UTC by Flaburgan

I played a bit with the header of the desktop version to improve its responsiveness.

The desktop menu didn't change:
**Before**
![screen shot 2017-07-31 at 21 34 35](https://user-images.githubusercontent.com/930064/28795408-07b74e54-763a-11e7-9bfc-0947d50894fa.png)
**After**
![screen shot 2017-07-31 at 21 34 47](https://user-images.githubusercontent.com/930064/28795409-07bb8294-763a-11e7-8459-66186e38d2a1.png)

The "Stream" and "My activity" links have been kept in the "tablet" breakpoint at 992px.
**Before**
![screen shot 2017-07-31 at 21 35 17](https://user-images.githubusercontent.com/930064/28795412-07c4dc68-763a-11e7-92e9-63e3022e1bf5.png)
**After**
![screen shot 2017-07-31 at 21 35 36](https://user-images.githubusercontent.com/930064/28795410-07be0384-763a-11e7-8230-2d4e43e307ed.png)

The pod name has been replace in mobile view, so the notification and conversation icons can be kept:
**Before**
![screen shot 2017-07-31 at 21 53 00](https://user-images.githubusercontent.com/930064/28795579-b6530fac-763a-11e7-8d51-e4739820dbf7.png)

**After**
![screen shot 2017-07-31 at 21 53 07](https://user-images.githubusercontent.com/930064/28795587-ba767970-763a-11e7-849e-8d939766f72e.png)

Also, I improved the menu by directly inserting the submenu for mobile and tablet (this didn't change for desktop):
**Before**
![screen shot 2017-07-31 at 21 53 16](https://user-images.githubusercontent.com/930064/28795594-c05a8e58-763a-11e7-8cc5-68159d1639ac.png)

**After**
![screen shot 2017-07-31 at 21 53 22](https://user-images.githubusercontent.com/930064/28795599-c544bd9e-763a-11e7-8abf-f23f3214a138.png)

This fixes https://github.com/diaspora/diaspora/issues/7019

2017-07-31 19:56 UTC, diaspora-code-review commented on app/assets/stylesheets/header.scss
> +        color: #9d9d9d;
Color literals like `#9d9d9d` should only be used in variable declarations; they should be referred to via variable everywhere else.

2017-07-31 19:56 UTC, diaspora-code-review commented on app/assets/stylesheets/header.scss
> +          color: #fff;
- Color literals like `#fff` should only be used in variable declarations; they should be referred to via variable everywhere else.
- Properties should be ordered background-color, color

2017-07-31 19:56 UTC, diaspora-code-review commented on app/assets/stylesheets/header.scss
> +  #header-title {
Avoid using id selectors

2017-07-31 19:56 UTC, diaspora-code-review commented on app/assets/stylesheets/header.scss
> +    #navbar-collapse {
Avoid using id selectors

2017-07-31 19:56 UTC, diaspora-code-review commented on app/assets/stylesheets/header.scss
> +    #user_menu.dropdown-menu {
- Avoid using id selectors
- Selector `user_menu` should be written in lowercase with hyphens

2017-07-31 19:56 UTC, diaspora-code-review commented on app/assets/stylesheets/header.scss
> +    #user_menu {
- Avoid using id selectors
- Selector `user_menu` should be written in lowercase with hyphens

2017-07-31 19:56 UTC, diaspora-code-review commented on app/assets/stylesheets/header.scss
> +        display: block !important;
!important should not be used

2017-07-31 19:56 UTC, diaspora-code-review commented on app/assets/stylesheets/header.scss
> +        &,
- Nesting should be no greater than 3, but was 4
- Selector should have depth of applicability no greater than 3, but was 4

2017-07-31 19:56 UTC, diaspora-code-review commented on app/assets/stylesheets/header.scss
> +        &:hover {
Nesting should be no greater than 3, but was 4

2017-07-31 19:56 UTC, diaspora-code-review commented on app/assets/stylesheets/header.scss
> +        > li > a {
- Nesting should be no greater than 3, but was 4
- Selector should have depth of applicability no greater than 3, but was 5

2017-07-31 19:56 UTC, diaspora-code-review commented on app/assets/stylesheets/header.scss
> +      display: block;
Properties should be ordered background-color, border, box-shadow, display, margin-top, padding, position, width

2017-07-31 19:56 UTC, diaspora-code-review commented on app/assets/stylesheets/header.scss
> +  .navbar-header > ul,
Selector should have depth of applicability no greater than 3, but was 4

2017-07-31 19:56 UTC, diaspora-code-review commented on app/assets/stylesheets/header.scss
> +          &:hover {
Selector should have depth of applicability no greater than 3, but was 5

2017-07-31 19:58 UTC, diaspora-code-review commented on app/assets/stylesheets/header.scss
> +        &:hover {
Selector should have depth of applicability no greater than 3, but was 4

2017-07-31 19:58 UTC, diaspora-code-review commented on app/assets/stylesheets/header.scss
> +      a {
Selector should have depth of applicability no greater than 3, but was 4

2017-07-31 21:40 UTC, diaspora-code-review commented on app/assets/stylesheets/header.scss
> +        color: #9d9d9d;
Color literals like `#9d9d9d` should only be used in variable declarations; they should be referred to via variable everywhere else.

2017-07-31 21:40 UTC, diaspora-code-review commented on app/assets/stylesheets/header.scss
> +          color: #fff;
Color literals like `#fff` should only be used in variable declarations; they should be referred to via variable everywhere else.

2017-07-31 21:40 UTC, diaspora-code-review commented on app/assets/stylesheets/header.scss
> +    #user-menu {
Avoid using id selectors

2017-07-31 21:40 UTC, diaspora-code-review commented on app/assets/stylesheets/header.scss
> +        &:hover {
Nesting should be no greater than 3, but was 4

2017-07-31 21:42 UTC, Flaburgan commented
I also improved the not connected header which now always displays the sign up and sign in links.

![screen shot 2017-07-31 at 22 27 08](https://user-images.githubusercontent.com/930064/28799649-c14663b4-7649-11e7-9329-6cfd10b8a5ed.png)

I wanted to finish this PR tonight but pronto is really too strong.

2017-08-01 01:31 UTC, denschub commented
I like it.

2017-08-01 20:18 UTC, Flaburgan commented on app/assets/stylesheets/header.scss
> +        color: #9d9d9d;
These colors are defined in bootstrap, how can I find which variable is it?

2017-08-01 20:30 UTC, SuperTux88 commented on app/assets/stylesheets/header.scss
> +        color: #9d9d9d;
You have the variables [here](https://github.com/diaspora/diaspora/blob/develop/app/assets/stylesheets/bootstrap-variables.scss) and you can search if you find it there. But that's probably not what you are looking for. When you know where this color is used in bootstrap, inspect the element in the browser, so you find the generated css from bootstrap in the browser. In the generated desktop.css there are comments above each rule, something like `/home/benjamin/.rvm/gems/ruby-2.4.0@diaspora/gems/bootstrap-sass-3.3.7/assets/stylesheets/bootstrap/...` then open that file and see which variable is used. Maybe there is an easier way, but I don't know it, that's what I did when I created the dark theme to find the variables I need to change.

2017-08-01 20:48 UTC, Flaburgan commented
I think I went deep enough with pronto. Removing the WIP status.
I keep the commits separated to ease the review, then I'll squash everything.
I tested these modifications with Firefox and Chromium.

2017-08-01 20:56 UTC, SuperTux88 commented
> I think I went deep enough with pronto.

👍 Please still fix the color variables (I tried to explain how to find the variables. I don't know if you understand it, if not ask me again in IRC, I think that's easier), but I think the others are OK for this PR.

2017-08-07 21:13 UTC, Flaburgan commented
Alright, I improved the colors management in themes and we now have no hardcoded values. I tested that with the default theme, original white and dark, everything should be okay.

This is ready to be reviewed. Once the review done, I'll squash the commits.

2017-08-10 12:20 UTC, svbergerem requested changes
Most of the comments are about the fixed vertical margins and paddings you used for the header. There is also a problem with the notification dropdown on small devices. I'll describe that in a comment below.

2017-08-10 12:21 UTC, svbergerem commented
Here is a diff with all proposed changes

```diff
diff --git a/app/assets/stylesheets/header.scss b/app/assets/stylesheets/header.scss
index d5723dce7..1bff67918 100644
--- a/app/assets/stylesheets/header.scss
+++ b/app/assets/stylesheets/header.scss
@@ -25,7 +25,7 @@
   }
 
   .header-title {
-    margin-top: -7px;
+    margin: (($navbar-height - 32px - 2 * $navbar-padding-vertical) / 2) 0;
 
     img {
       height: 32px;
@@ -50,7 +50,7 @@
   }
 
   .nav-badge {
-    padding: 16px 12px;
+    padding: $navbar-padding-vertical 12px;
 
     .badge {
       position: absolute;
@@ -136,11 +136,17 @@
     }
   }
 
+  .navbar-form .form-control { display: inline-block; }
+
   @media (max-width: $grid-float-breakpoint-max) {
 
     .navbar-nav.hidden-xs {
       margin: 0;
-      margin-top: 6px;
+
+      a {
+        padding-bottom: $navbar-padding-vertical;
+        padding-top: $navbar-padding-vertical;
+      }
     }
 
     .nav-badge {
@@ -164,12 +170,20 @@
       width: 300px;
     }
 
+    .navbar-collapse {
+      padding-top: $navbar-padding-vertical / 2;
+
+      .navbar-nav {
+        margin-bottom: 0;
+        margin-top: 0;
+      }
+    }
+
     .user-menu-dropdown {
       background-color: transparent;
       border: 0;
       box-shadow: none;
       display: block;
-      margin-top: -8px; // To compensate parent ul margin
       padding: 0;
       position: static;
       width: 100%;
@@ -177,7 +191,7 @@
       a {
         color: $navbar-inverse-link-color;
         font-weight: bold;
-        padding: 10px 15px;
+        padding: $nav-link-padding;
 
         &:hover {
           background-color: $navbar-inverse-link-hover-bg;
@@ -189,9 +203,13 @@
 
   @media (min-width: $grid-float-breakpoint) {
 
+    .navbar-form { // set correct margin for small inputs
+      margin-bottom: ($navbar-height - $input-height-small) / 2;
+      margin-top: ($navbar-height - $input-height-small) / 2;
+    }
+
     [type="search"] {
       @include transition(width);
-      margin-top: 2px;
       width: 200px;
 
       &:not(.active) {
```

2017-08-10 12:29 UTC, svbergerem commented
On small devices (e.g. Nokia Lumia 520) the notification dropdown is too big.

![screen shot 2017-08-10 at 14 03 49](https://user-images.githubusercontent.com/3798614/29170115-67a8df68-7dd7-11e7-9390-3686f41bcdde.png)
![screen shot 2017-08-10 at 14 03 53](https://user-images.githubusercontent.com/3798614/29170116-67aabd24-7dd7-11e7-8dc3-f3628380d7ae.png)

One could detect small devices (<768px) by looking for the `.header-title` and follow the link instead of opening the dropdown. We did something similar with [this line](https://github.com/diaspora/diaspora/blob/9d2d20e85471ef5b13c591cc25e69bf583d8c49e/app/assets/javascripts/app/views/notification_dropdown_view.js#L29) which is now obsolete, because the `.entypo-bell` is always visible.

2017-08-10 12:41 UTC, SuperTux88 commented
> and follow the link instead of opening the dropdown.

I think the dropdown is cool, without the need to load a new page. Can we just set the size of the dropdown to full-screen-size for small devices, instead of a fixed width with pixels?

2017-08-10 13:27 UTC, svbergerem commented
@SuperTux88 For devices <768px:
![screen shot 2017-08-10 at 15 25 27](https://user-images.githubusercontent.com/3798614/29172526-761c9658-7de0-11e7-89e0-022f3c1faa16.png)
![screen shot 2017-08-10 at 15 25 03](https://user-images.githubusercontent.com/3798614/29172525-761a6536-7de0-11e7-8132-22aa8c935f79.png)

2017-08-10 13:29 UTC, SuperTux88 commented
Looks great ❤️

2017-08-10 13:57 UTC, svbergerem commented
@Flaburgan I just added some new commits. All builds were failing before and I only checked that my JavaScript changes don't break new tests. Let me know if you need some help fixing the tests.

2017-08-10 16:47 UTC, svbergerem approved these changes

2017-08-10 16:49 UTC, merged

2017-08-10 16:49 UTC, svbergerem commented
Thank you! :)

2017-08-11 07:36 UTC, Flaburgan commented
Thank you for the polishing ;)

2018-04-07 12:30 UTC, paskalito commented
@fla so cool!! thanks a lot for that cool new great solution!