Cleanup .gitignore and add note about .well-known to the changelog
diaspora/diaspora pull request #7512
Opened 2017-08-03 22:45 UTC by SuperTux88

I noticed that some pods still have a static `/.well-known/host-meta` from the past. That wasn't a problem, because the old file had the same content as the generated version from the federation lib. But with the new federation-lib 0.2.0 the content changed, and with the old static file webfinger doesn't work anymore. So I added a note to the changelog, so people need to check if they have an old cached `public/.well-known` and if so, delete it.

I also cleaned up some other old unused lines from the `.gitignore`.

2017-08-03 22:49 UTC, skyschub approved these changes

2017-08-03 22:50 UTC, cmrd-senya commented on Changelog.md
> +Before upgrading, please check if your `publlic/` folder contains a hidden `.well-known` folder.
typo: "publ**l**ic"

2017-08-03 22:51 UTC, skyschub requested changes
Oh noez! See senyas comment!

2017-08-03 22:51 UTC, denschub commented on Changelog.md
> +Before upgrading, please check if your `publlic/` folder contains a hidden `.well-known` folder.
And this, ladies and gentleman, is the reason why I should not approve sentences I wrote myself!

2017-08-03 22:52 UTC, SuperTux88 commented on Changelog.md
> +Before upgrading, please check if your `publlic/` folder contains a hidden `.well-known` folder.
Fixed, thanks 👍 (RubyMine has a spellchecker ... but since it's in `...` it didn't check it ;) )

2017-08-03 22:55 UTC, skyschub approved these changes

2017-08-04 01:10 UTC, merged

2017-08-04 07:46 UTC, Flaburgan commented
I do have a `.well-known` folder in `public/` but that's where I have the acme-challenge for Let's Encrypt. We should probably be more precise about this folder and what's in which could block the federation, to tell everyone to delete doesn't seem careful.