Account deletion memory leak
diaspora/diaspora pull request #7639
Opened 2017-10-12 17:43 UTC by SuperTux88

This massively reduces the memory usage for account deletions (which could cause OOMs when deleting many big accounts in parallel). With this PR the sidekiq process uses only 180MB ram after deleting a rss-bot account with 17k posts (after start sidekiq uses 150MB, so this is only 30MB more than after start). Without this PR the same account deletion used 1.8GB ram.

I also did some cleanups in the `AccountDeleter` and added a check for duplicate account deletions.

2017-10-12 21:58 UTC, goobertron commented
Whooooooooooo! 

Another fantastic performance improvement. Thanks!

2017-10-15 21:11 UTC, denschub commented
I wonder if we should create a short rake task to run old account deletions, so people can re-run them. What do you think?

2017-10-15 21:21 UTC, skyschub requested changes
As discussed on a private channel, let's add a rake task. Nobody will probably see it, and we can only put it into the 0.8.0.0 upgrade instructions, but it does not cause any harm if we ship it earlier.

Other than that, code looks fine.

2017-10-15 22:31 UTC, SuperTux88 commented
I added the rake task, but this also depends on #7632 to fix another account deletion related bug.

2017-10-16 01:17 UTC, skyschub approved these changes

2017-10-16 23:40 UTC, closed without merging

2017-10-16 23:41 UTC, SuperTux88 commented
Merged as 2bd9c663c509f4f5d1ccae0e20fa13e220510627, 6d5647ec112d3fd0c93d7f217dc2f6beed9fde04, b920ddbff55dd0facd54da884943d16e568860f2, f704f305727feeb9fa528de6a08ded56d40674d2, f4902421eaa50dea98dc5046848f95c959cb3c88 and 4e6d92ce63c96d577cef04e338bed8a17372b635

Thanks for the review @denschub 🍪