Fix deformed avatar in hovercards
diaspora/diaspora pull request #7656
Opened 2017-10-30 22:59 UTC by Flaburgan

So, from the [different options](https://github.com/diaspora/diaspora/issues/6039#issuecomment-339945467), I went the safest way: keep the avatar to 70x70 and truncate the image as done for the `small` avatar everywhere else. The "truncation" is not really one: I simply set the image as a background one and center center in a 70x70 container.

Fixes #6039

2017-11-02 03:26 UTC, SuperTux88 requested changes
Thanks for the PR, while this fixed the deformed avatars, it breaks some other things:

* It doesn't have rounded corners anymore.
* The error handling doesn't work anymore. When the avatar doesn't exist anymore or couldn't be loaded, it just displays an empty box instead of the default avatar:

https://github.com/diaspora/diaspora/blob/1c1af74e9f3cfc5f54ba07ecec78ccc1a6379308/app/assets/javascripts/app/views.js#L158-L160

2017-11-07 22:55 UTC, Flaburgan commented
I don't reproduce your problem with Firefox and Chromium. The avatar is rounded and the default avatar is here. It was not correctly displayed so I added `background-position: cover;`. On which page and with which browser did you test this code?

2017-11-09 01:31 UTC, SuperTux88 commented
> The avatar is rounded

Ok, that was "my fault", I didn't look close enough ... it is indeed rounded ... but I didn't see it, because I uploaded a full-hd (1920x1080) Image, which was then resized to 100x63, which is too small to see the corners ... so it's just another problem that was visible there.

Also, when uploading a perfectly squared avatar, you see the opposite problem, the avatar is displayed too big (because you use the 100x100 image as background). Here you see an example with the small avatar beside it, so you can see how it should look:

![](https://user-images.githubusercontent.com/458548/32583499-1fe616b4-c4f4-11e7-817e-66e748f72350.png)

It's even worse with a user from friendica, where the avatar is 175x175:

![](https://user-images.githubusercontent.com/458548/32583554-6d0add08-c4f4-11e7-9cd4-14f5c7f0c89c.png)

> and the default avatar is here.

No, when the avatar isn't available anymore (deleted or down), there is just a blank space. Here is a screenshot of it, and you see that the fallback still works with the avatar beside it, where the linked code above sets the default avatar when the linked avatar isn't available, but it doesn't work for the background avatar:

![](https://user-images.githubusercontent.com/458548/32583728-84b5f5cc-c4f5-11e7-924f-1aa8ee8ba481.png)

> On which page and with which browser did you test this code?

Tested with both firefox and chromium, at stream and single-post-view.

2017-11-09 09:03 UTC, Flaburgan commented
>No, when the avatar isn't available anymore (deleted or down)

Oh, that was the use case. I tried with a user who never uploaded an avatar. I'm going to look at that, thank you.

2017-11-10 12:02 UTC, Flaburgan commented
>Also, when uploading a perfectly squared avatar, you see the opposite problem, the avatar is displayed too big

Aaaaaand this one is my fault, I test CSS directly in Firefox because the page is slow to load in dev mode, and I wrote `background-position: cover;` when it should have been `background-size: cover;`. My bad, this is now fixed and the avatar should display correctly. Now let me check the default avatar issue.

2017-11-10 12:42 UTC, Flaburgan commented
Alright so forget about this CSS approach with background image, to have the avatar fallback it was way easier to keep the HTML one. I had to do some research but I discovered exactly what we wanted: the [object-fit](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) property. Way cleaner code, isn't it? I just had to add this line. (I still cleaned the `!important` mention as I hate it and it looks like they were useless with Firefox and Chrome. Let's test in `develop` if that's really true).

For information, the browser support of `object-fit` is Chrome 31, Edge 16 and Firefox 36. No IE, but the consequence is a deformed avatar like the current situation so we should be good 👍

2017-12-17 07:44 UTC, SuperTux88 approved these changes
Tested and works as expected 👍 

> For information, the browser support of object-fit is Chrome 31, Edge 16 and Firefox 36. No IE, but the consequence is a deformed avatar like the current situation so we should be good 👍

Agree 👍

2017-12-18 03:42 UTC, closed without merging

2017-12-18 03:43 UTC, SuperTux88 commented
Merged as 53603917eba5cb91bd824304ff2e6ad3b2e44150

Thank you 🍪