Enable Content-Security-Policy header by default
diaspora/diaspora pull request #7781
Opened 2018-04-10 00:32 UTC by SuperTux88

After 0.7.4.1 I think it's a good time to enable this by default ;) It's working without any problems in productions for a long time now, so I think it's save to enable it everywhere. Since this is a config-change and some podmins may have customization which could be blocked by this, I think we should still only change it in the next major release.

2018-04-10 00:39 UTC, skyschub approved these changes
I have no objections here, so I'm approving this PR. However, I suggest not merging it now, but waiting for a few days, so others have a chance to jump in as well.

2018-04-10 07:01 UTC, Flaburgan requested changes

2018-04-10 07:01 UTC, Flaburgan commented on config/diaspora.yml.example
>        ## this to false, the "Content-Security-Policy" header is added instead.
This comment also needs to be updated.

2018-04-10 19:30 UTC, SuperTux88 commented on config/diaspora.yml.example
>        ## this to false, the "Content-Security-Policy" header is added instead.
Of course, fixed.

2018-04-24 14:37 UTC, pacohope commented
I've been running with the CSP enabled and I found a bug. Fonts were not covered by the CSP if they were distributed through an asset host. I created a PR for a one-line change that fixes it. #7796 You might want to incorporate it and/or merge it with this.

2018-06-16 00:57 UTC, SuperTux88 commented
Since #7796 is merged now, I think we can merge this too? Can you please approve your review @Flaburgan since your requested change is already fixed.

2018-06-16 07:24 UTC, Flaburgan approved these changes

2018-06-16 10:11 UTC, jhass approved these changes

2018-06-16 19:23 UTC, merged