Add unique index to poll participations on author_id and poll_id
diaspora/diaspora pull request #7798
Opened 2018-04-25 13:41 UTC by cmrd-senya

Previously we had only a Rails validation which ensured poll participation
uniqueness but this adds uniqueness control to the database level, so that
uniqueness is guaranteed even when changing data with avoiding Rails
validations.

2018-04-30 21:34 UTC, SuperTux88 requested changes
When there wasn't a unique index before, you should remove potential duplicates (although there are probably none) before adding the index to make sure the index can be created.

2018-05-01 08:05 UTC, CSammy commented
I suggest that we do the index the other way around - `%i[poll_id author_id]` - and get rid of the index on `poll_id` in order to keep index overhead down on both storage and performance.

2018-05-03 14:50 UTC, cmrd-senya commented
Updated

2018-05-03 19:17 UTC, SuperTux88 approved these changes

2018-05-03 19:33 UTC, closed without merging

2018-05-03 19:33 UTC, SuperTux88 commented
Merged as e9f6dbdffd8b9c74238e1183cff3918a487e4a89

Thank you :cookie: