7900-In single post view deleting a comment updates the counter
diaspora/diaspora pull request #7938
Opened 2018-11-24 09:00 UTC by tclaus

Added removeComment event in interactions to update the comments-counter after remove

2018-11-24 09:01 UTC, diaspora-code-review commented on app/assets/javascripts/app/models/post/interactions.js
> +      this.set({"comments_count": this.get("comments_count") - 1});
Expected indentation of 4 space characters but found 6.

2018-11-24 09:01 UTC, diaspora-code-review commented on app/assets/javascripts/app/views/comment_stream_view.js
> +    if (result.hasClass('deleting') ) {
- Strings must use doublequote.
- There should be no spaces inside this paren.

2018-12-02 07:37 UTC, tclaus commented
BTW: Solves Issue #7938

2018-12-04 15:38 UTC, HankG commented
I've pulled this down and confirm that this resolves the bug in #7900 .  I believe this is ready to be merged.

2018-12-21 23:33 UTC, HankG approved these changes

2018-12-30 23:33 UTC, Flaburgan requested changes
Sorry for the late review, and thank you for your work!
I tested your code and it works well. It would be awesome however if you could [write a test](https://wiki.diasporafoundation.org/Testing_workflow) for it. A Jasmine one could be enough, add it in `/spec/javascripts/app/views/single-post-view/single_post_interaction_counts_spec.js`.

You can then squash your commits (with `git fetch upstream`, `git rebase -i upstream/develop` then replacing `pick` by `f` for the commits below the first one) and you'll be ready to go!

2019-02-12 07:08 UTC, tclaus commented
@Flaburgan Sorry - I checked the Jasmine tests but I have no clue how to set a comment, get the current number displayed and then remove a comment and check the displayed number again. Can someone take over the tests part or give me a deeper advice?

2019-07-24 08:01 UTC, ThorstenClaus commented
@denschub Any progress here?

2020-10-23 05:51 UTC, tclaus commented
@denschub Mention for reviewing this. Base code has changed over time - is this still a valid PR or can this be closed now?

2020-10-24 12:26 UTC, denschub commented
Sorry. I wanted to write a test, but then never did. I'm also not really in the mood today, so.. let's just merge this without tests.

Merged as https://github.com/diaspora/diaspora/commit/d0eb711ca0ac1541756d2f25d963095a3236db11.

2020-10-24 12:26 UTC, closed without merging