8018 Do not show getting started after account import
diaspora/diaspora pull request #8036
Opened 2019-06-26 07:21 UTC by theRealNG

2019-06-26 07:21 UTC, diaspora-code-review commented on spec/lib/archive_importer_spec.rb
> +          "getting_started"                    => false,
Style/TrailingCommaInHashLiteral: Avoid comma after the last item of a hash.

2019-06-26 07:21 UTC, diaspora-code-review commented on spec/lib/archive_importer_spec.rb
> +      expect(archive_importer.user.getting_started).to eq(archive_hash['user']['getting_started'])
Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.

2019-06-26 07:38 UTC, Flaburgan commented
Hi @theRealNG and thank you for your work! Did you check that `getting_started` was actually part of the exported archive? I'm not sure it is included.

2019-06-26 07:54 UTC, jhass commented
Looking at https://github.com/diaspora/diaspora/blob/develop/app/serializers/export/user_serializer.rb I don't think it's imported.

I think it's also useful to default to `false` for archive's  that don't contain it.

2019-06-26 07:59 UTC, Flaburgan commented
>I think it's also useful to default to false for archives that don't contain it.

Yep, we definitely don't want to break compatibility with archives generated until now, so either add it to the archive but don't fail if not present by setting it to false, or just always set it to false, that looks fine to me.

2019-06-26 08:29 UTC, theRealNG commented
Thinking of going with always setting it to false

2019-06-26 09:22 UTC, theRealNG commented
@Flaburgan & @jhass Pushed changes that always set the `getting_started` as false while importing a user profile.

2019-06-26 09:29 UTC, jhass approved these changes
This is fine to me, @SuperTux88 wished for transfering the status of the source account so he should say if this is a no-go for him for some reason :)

2019-06-26 09:37 UTC, Flaburgan requested changes

2019-06-26 09:37 UTC, Flaburgan commented on lib/archive_importer.rb
> +    # so the user need not see the getting_started wizard
I'm not a native speaker but I feel like "the user doesn't need to see the getting started wizard" sounds better.

2019-06-26 10:11 UTC, SuperTux88 commented
> @SuperTux88 wished for transfering the status of the source account so he should say if this is a no-go for him for some reason :)

Oh no, I didn't wish that, I even wrote that setting it to always false would be a solution, so that's perfectly fine for me. :+1: Fla wanted it copied from the old pod.

2019-06-26 10:14 UTC, SuperTux88 approved these changes
LGTM :cookie: 

(maybe squash your commits to a single one, ask if you don't know how to do that, but we can also do that when merging it)

2019-06-26 10:15 UTC, Flaburgan approved these changes

2019-07-03 11:34 UTC, merged

2019-07-03 11:37 UTC, SuperTux88 commented
Merged, thanks for your contribution @theRealNG :cookie: 

(I also just saw that you developed that change on your `develop`-branch, you should do that on a separate branch next time, so `develop` can stay clean to branch of it)