Remove the JSXC/Prosody integration.
diaspora/diaspora pull request #8069
Opened 2019-10-18 03:54 UTC by denschub

As per discussion on https://discourse.diasporafoundation.org/t/removing-diaspora-s-current-chat-integration/2718, nobody raised serious concerns or objections. Given future plans, we do not think having an unfinished implementation of something that likely will not get finished in the current form is worth it. So let's get rid of it.

I deliberately ignored all codestyle warnings. As this PR is exclusively removing things, I felt better not touching anything. Happy to change things if someone feels like it.

When merged, this PR needs documentation in the Changelog that explains the implications.

2019-10-18 03:55 UTC, diaspora-code-review commented on app/assets/javascripts/app/views/help_view.js
> +      title_miscellaneous: Diaspora.I18n.t( 'miscellaneous.title' )
- Identifier 'title_miscellaneous' is not in camel case.
- There should be no spaces inside this paren.
- Strings must use doublequote.

2019-10-18 03:55 UTC, diaspora-code-review commented on spec/integration/exporter_spec.rb
> +              "name":             "generic"
Layout/AlignHash: Align the elements of a hash literal if they span more than one line.

2019-10-18 03:55 UTC, diaspora-code-review commented on spec/integration/exporter_spec.rb
> +              "name":             "Work"
Layout/AlignHash: Align the elements of a hash literal if they span more than one line.

2019-10-18 03:55 UTC, diaspora-code-review commented on spec/serializers/export/aspect_serializer_spec.rb
> +      name:         aspect.name
Layout/ExtraSpacing: Unnecessary spacing detected.

2019-10-18 17:30 UTC, SuperTux88 requested changes
Overall this looks good to me. I know you ignored codestyle-warnings, but I would still suggest fixing the last 3 warnings about alignment and spacing (I think that improves code quality at these places with only little changes of whitespace), I'm fine with ignoring the first one about camelcase and stuff.

Also, I found the one below, which I think is worth fixing, even not directly related to chat removing.

2019-10-18 20:58 UTC, denschub commented on spec/integration/migration_service_spec.rb
> +          {"name":"Friends"}
I... have no idea why that's there. Probably an oversight from adding the chat tests and not noticing the names.

2019-10-18 21:14 UTC, diaspora-code-review commented on app/assets/javascripts/app/views/help_view.js
> +      title_header: Diaspora.I18n.t("title_header"),
Identifier 'title_header' is not in camel case.

2019-10-18 21:14 UTC, diaspora-code-review commented on app/assets/javascripts/app/views/help_view.js
> +      title_getting_help: Diaspora.I18n.t("getting_help.title"),
Identifier 'title_getting_help' is not in camel case.

2019-10-18 21:14 UTC, diaspora-code-review commented on app/assets/javascripts/app/views/help_view.js
> +      title_account_and_data_management: Diaspora.I18n.t("account_and_data_management.title"),
Identifier 'title_account_and_data_management' is not in camel case.

2019-10-18 21:14 UTC, diaspora-code-review commented on app/assets/javascripts/app/views/help_view.js
> +      title_aspects: Diaspora.I18n.t("aspects.title"),
Identifier 'title_aspects' is not in camel case.

2019-10-18 21:14 UTC, diaspora-code-review commented on app/assets/javascripts/app/views/help_view.js
> +      title_mentions: Diaspora.I18n.t("mentions.title"),
Identifier 'title_mentions' is not in camel case.

2019-10-18 21:14 UTC, diaspora-code-review commented on app/assets/javascripts/app/views/help_view.js
> +      title_pods: Diaspora.I18n.t("pods.title"),
Identifier 'title_pods' is not in camel case.

2019-10-18 21:14 UTC, diaspora-code-review commented on app/assets/javascripts/app/views/help_view.js
> +      title_posts_and_posting: Diaspora.I18n.t("posts_and_posting.title"),
Identifier 'title_posts_and_posting' is not in camel case.

2019-10-18 21:14 UTC, diaspora-code-review commented on app/assets/javascripts/app/views/help_view.js
> +      title_private_posts: Diaspora.I18n.t("private_posts.title"),
Identifier 'title_private_posts' is not in camel case.

2019-10-18 21:14 UTC, diaspora-code-review commented on app/assets/javascripts/app/views/help_view.js
> +      title_public_posts: Diaspora.I18n.t("public_posts.title"),
Identifier 'title_public_posts' is not in camel case.

2019-10-18 21:14 UTC, diaspora-code-review commented on app/assets/javascripts/app/views/help_view.js
> +      title_resharing_posts: Diaspora.I18n.t("resharing_posts.title"),
Identifier 'title_resharing_posts' is not in camel case.

2019-10-18 21:14 UTC, diaspora-code-review commented on app/assets/javascripts/app/views/help_view.js
> +      title_sharing: Diaspora.I18n.t("sharing.title"),
Identifier 'title_sharing' is not in camel case.

2019-10-18 21:14 UTC, diaspora-code-review commented on app/assets/javascripts/app/views/help_view.js
> +      title_tags: Diaspora.I18n.t("tags.title"),
Identifier 'title_tags' is not in camel case.

2019-10-18 21:14 UTC, diaspora-code-review commented on app/assets/javascripts/app/views/help_view.js
> +      title_keyboard_shortcuts: Diaspora.I18n.t("keyboard_shortcuts.title"),
Identifier 'title_keyboard_shortcuts' is not in camel case.

2019-10-18 21:14 UTC, diaspora-code-review commented on app/assets/javascripts/app/views/help_view.js
> +      title_miscellaneous: Diaspora.I18n.t("miscellaneous.title")
Identifier 'title_miscellaneous' is not in camel case.

2019-10-18 21:25 UTC, SuperTux88 approved these changes
Thanks for the changes, looks good to me :cookie:

2019-10-24 23:35 UTC, SuperTux88 commented
Merged to `develop`, thanks :cookie:

2019-10-24 23:35 UTC, merged