Drop spring
diaspora/diaspora pull request #8133
Opened 2020-07-10 12:03 UTC by jhass

it does more harm than good at this point

2020-07-10 14:59 UTC, skyschub approved these changes

2020-07-11 00:56 UTC, SuperTux88 requested changes
There is also `config/spring.rb` which can be deleted now.

Otherwise looks good to me :cookie:

2020-09-03 20:51 UTC, SuperTux88 approved these changes

2020-09-04 20:02 UTC, jhass commented
Merged as ce82ba3dde7178b6e707d83bc6246fe033a328c9

2020-09-04 20:02 UTC, closed without merging