Add a max-width to user name in the header, fixes #7676
diaspora/diaspora pull request #8313
Opened 2021-10-28 21:43 UTC by Flaburgan

300px is small enough, if the screen width get small the header becomes responsive so the user name is not displayed anymore.

2021-10-30 00:30 UTC, SuperTux88 requested changes
Looks good otherwise

2021-10-30 00:30 UTC, SuperTux88 commented on app/assets/stylesheets/header.scss
> +      display: inline-block;
I think this isn't needed, at least my browser (firefox and chrome) is telling me, that it's using `display: block` anyway and just ignores it.

2021-10-30 01:37 UTC, SuperTux88 commented
Oh, I also think 300px is too much, it works with English, but still breaks with some other languages (German for example). So maybe just reduce it to 250px so we have some more space for languages with longer texts in the header?

2021-10-30 09:53 UTC, Flaburgan commented
Done. I also added a small margin between the name and the caret.

2021-10-30 20:24 UTC, SuperTux88 approved these changes

2021-11-23 00:08 UTC, closed without merging

2021-11-23 00:08 UTC, SuperTux88 commented
Merged as 37f081959c8ea1aad7bd23481a34d8ca5815bb13

Thanks for the fix :cookie: