Do not show the service to the user if it is disabled, fixes #6184
diaspora/diaspora pull request #8406
Opened 2022-10-31 16:40 UTC by Flaburgan

2022-10-31 22:34 UTC, denschub commented
This breaks Jasmine, there are specs that have expectations around available services that are no longer true with this PR.

2022-10-31 22:35 UTC, denschub requested changes
(see previous comment)

2022-10-31 23:00 UTC, diaspora-code-review commented on spec/javascripts/app/views/publisher_view_spec.js
> +      gon.appConfig = {configured_services: ["twitter", "tumblr"]};
Identifier 'configured_services' is not in camel case.

2022-10-31 23:01 UTC, Flaburgan commented
Yep, it should be fixed now. I had to switch to another computer so it took time for `diaspora-dev setup` to run.
Should I also add a test to test the code I wrote? Should it be rspec or cucumber?

2022-11-05 09:26 UTC, Flaburgan commented
OK so I'm confused @SuperTux88 said this to me on IRC:

>the jasmine spec is probably broken because it generates the templates with different settings ... the change you made in `publisher_view_spec.js` doesn't affect `_publisher.html.haml` so you need to change the configured services in the rspec test that generates the template that is used for the failing jasmine test ... and to test that locally you need to re-generate the fixtures locally, because you probably still have them from before your change

But actually locally the jasmine tests are green without adding anything else that what I did here. What you are saying is that I should also modify `publisher_spec.rb`?

2022-11-06 00:31 UTC, SuperTux88 commented
> But actually locally the jasmine tests are green without adding anything else that what I did here. What you are saying is that I should also modify `publisher_spec.rb`?

When I wrote that I didn't check which fixture is used and where it's generated. I assumed that you didn't re-generate your fixtures locally, so you are still using fixtures that were generated before your change in `_publisher.html.haml`. And the change you did to `publisher_view_spec.js` isn't needed and doesn't change anything, as it doesn't affect the fixture (locally your tests are probably green with or without that change there? But if you re-generate fixtures with `bin/rake tests:generate_fixtures`, then I assume that your tests aren't green anymore).

So in the line below the line you added, you see it loads `aspects_index_services`, and that one is generated in `aspects_spec.rb`, so you need to change that so the fixture still contains the services, and then jasmine will work again.

2023-02-07 22:13 UTC, Flaburgan commented
The related tests are fixed, the current failure in Rspec is unrelated, `develop` is also failing on that test. So this should be ready for review.

2023-02-07 22:59 UTC, denschub approved these changes
Ideally, this would have a test with a service that's disabled globally but enabled in the user settings, and then confirming that the button isn't showing up. Writing a test for the actual behavior change here, that is.

But I feel adventurous today, so I'm personally not gonna block on that.

2023-06-03 23:20 UTC, SuperTux88 requested changes

2023-06-03 23:20 UTC, SuperTux88 commented on app/views/publisher/_publisher.html.haml
>              - if current_user.services
Sidenote, as you didn't change it here, but I don't think this `if` is needed, as if there are no services, the list would just be empty, so there is nothing to loop over anyway?

2024-06-02 03:03 UTC, SuperTux88 reviewed
> However, it is hard to test as I can't enable services for my user locally (if you can tell me how to do that).

Just create a dummy service with dummy data on the user manually. You won't be able to post to it, but you can test if the buttons show:

```ruby
user = User.find_by(username: "test")
user.services << Services::Tumblr.new(nickname: "nick", access_token: "token", access_secret: "secret", uid: "uid", provider: "Tumblr")
user.services << Services::Wordpress.new(nickname: "nick", access_token: "token", access_secret: "secret", uid: "uid", provider: "Wordpress")
```

2024-06-02 03:11 UTC, SuperTux88 commented
I removed your last commit, and added my own with the helper that just filters the services and also added a test for that helper.

This now just filters the services for both UIs (so fixes the bug for both of them), but keeps the design otherwise as is.

2024-06-02 03:41 UTC, denschub approved these changes

2024-06-02 10:40 UTC, Flaburgan commented
Thank you for finishing this

2024-06-04 23:08 UTC, merged