Tell users that there is no help in mobile version, allow to switch to desktop
diaspora/diaspora pull request #8407
Opened 2022-10-31 23:37 UTC by Flaburgan

Fixes #4821

2022-10-31 23:37 UTC, diaspora-code-review commented on app/views/help/faq.mobile.haml
> +%p= link_to(t("layouts.application.switch_to_standard_mode"), toggle_mobile_path)
Files should end with a trailing newline

2022-11-01 19:44 UTC, SuperTux88 requested changes
First, the tests now fail because the page now "exists" on mobile.

Also, I would use the same design as is already used on `/admin/pods`, so we don't have two different ways of showing the same:
![image](https://user-images.githubusercontent.com/458548/199324229-aa96b528-15b9-47a3-b7ab-878e3961949d.png)

2022-11-02 22:24 UTC, diaspora-code-review commented on app/views/admins/pods.mobile.haml
> +  != t("error_messages.mobile_not_available", desktop_link: link_to(t("error_messages.desktop_view_link"), toggle_mobile_path))
Line is too long. [127/120]

2022-11-02 22:24 UTC, diaspora-code-review commented on app/views/help/faq.mobile.haml
> +  != t("error_messages.mobile_not_available", desktop_link: link_to(t("error_messages.desktop_view_link"), toggle_mobile_path))
Line is too long. [127/120]

2022-11-02 22:29 UTC, Flaburgan commented
@SuperTux88 I changed the translations keys so we can reuse them, the text actually is generic. Can you or @jhass do the action needed so it doesn't have to be re-translated?

2022-11-04 01:02 UTC, SuperTux88 approved these changes
LGTM :cookie:

2022-11-04 01:11 UTC, merged

2022-11-04 01:11 UTC, SuperTux88 commented
Merged and translations updated.