docker-compose.yml - bump mariadb version
diaspora/diaspora pull request #8452
Opened 2024-08-30 08:24 UTC by grooverdan

Noted its not the primary development environment, but 10.9 is out of support so just keep the the LTS tag.

MARIADB_AUTO_UPGRADE=1 facilitates in place upgrades.

2024-08-31 00:01 UTC, SuperTux88 requested changes
The upgrade is fine, and if it auto-upgrades the data, even better (but since this is only for development, it would be also fine if you need to start with a fresh database every now and then). :+1: 

But renaming the container won't work, as it's expected to be named `mysql` by the scripts and the other configs.

2024-09-04 23:38 UTC, SuperTux88 approved these changes

2024-09-04 23:40 UTC, closed without merging

2024-09-04 23:41 UTC, SuperTux88 commented
Merged as 53b9e3cbf30bc9bdabb235569711913fe1bc4d35, thanks for the fix :cookie:

2024-09-05 05:57 UTC, grooverdan commented
Easy. Thanks for the merge and current MariaDB support.